[package]
name = "tsuburu-dialogue"
version = "0.3.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tsuburu-text = { path = "../tsuburu-text" }
redb = "2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
lz4_flex = { version = "0.11", default-features = false, features = ["safe-encode", "safe-decode", "std"] }
sha2 = "0.10"
memchr = "2"
memmap2 = "0.9"

[dev-dependencies]
tempfile = "3"
