[package]
name = "tsuburu-store"
version = "0.3.15"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
redb = "2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
directories = "6"

[dev-dependencies]
tempfile = "3"
