[package]
name = "tsuburu-keywords"
version = "0.3.10"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
redb = "2"
thiserror = { workspace = true }
tracing = { workspace = true }
lz4_flex = { version = "0.11", default-features = false, features = ["safe-encode", "safe-decode", "std"] }

[dev-dependencies]
tempfile = "3"
